version: 2
updates:

  # Keep GitHub Actions used in workflows up to date.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "emaarco"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
